
////////////////////////////////////////////////////////////////////////////////

//  Copyright (c) 2019, Perry L Miller IV
//  All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
//
//  Main file for test program.
//
////////////////////////////////////////////////////////////////////////////////

#define CATCH_CONFIG_RUNNER
#include "catch2/catch.hpp"

#include <iostream>


////////////////////////////////////////////////////////////////////////////////
//
//  Main function.
//
////////////////////////////////////////////////////////////////////////////////

int main ( int argc, char **argv )
{
  int result ( 1 );

  try
  {
    result = Catch::Session().run ( argc, argv );
  }

  catch ( const std::exception &e )
  {
    std::cout << "Standard exception caught: " << e.what() << std::endl;
  }

  catch ( ... )
  {
    std::cout << "Unknown exception caught" << std::endl;
  }

  return result;
}
